language: python

python:
  - "2.7"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - python setup.py install

# command to run tests
script:
    - nosetests --with-coverage --cover-erase --cover-html --cover-package=widgets

after_success:
    - codeclimate-test-reporter
    - coverage xml
    - python-codacy-coverage -r coverage.xml

# Blacklist
branches:
  except:
    - gh-pages
